title: Program
modelClass: Lfi\Formations\Models\Program
list: $/lfi/formations/models/program/columns.yaml
recordUrl: 'lfi/formations/program/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
