list: $/lfi/formations/models/partners/columns.yaml
modelClass: Lfi\Formations\Models\Partners
title: Partners
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'lfi/formations/partners/update/:id'
