title: Formations
modelClass: Lfi\Formations\Models\Formation
list: $/lfi/formations/models/formation/columns.yaml
recordUrl: 'lfi/formations/formations/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
