list: $/lfi/formations/models/day/columns.yaml
modelClass: Lfi\Formations\Models\Day
title: Days
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'lfi/formations/days/update/:id'
