plugin:
    name: 'lfi.formations::lang.plugin.name'
    description: 'lfi.formations::lang.plugin.description'
    author: lfi
    icon: oc-icon-book
    homepage: ''
navigation:
    main-menu-item:
        label: FORMATIONS
        url: lfi/formations/formations
        icon: icon-book
        sideMenu:
            side-menu-item:
                label: Formations
                url: lfi/formations/formations
                icon: icon-book
            side-menu-item2:
                label: Catégories
                url: lfi/formations/category
                icon: icon-tags
            programme:
                label: 'Modules Generaux'
                url: lfi/formations/program
                icon: icon-clipboard
            professionals:
                label: 'Modules Professionnels'
                url: lfi/formations/professional
                icon: icon-clipboard
            side-menu-item3:
                label: Témoignages
                url: lfi/formations/interview
                icon: icon-users
            side-menu-item4:
                label: Financement
                url: lfi/formations/finance
                icon: icon-money
    partners:
        label: PARTENAIRE
        url: lfi/formations/partners
        icon: icon-connectdevelop
