list: $/lfi/formations/models/finance/columns.yaml
modelClass: Lfi\Formations\Models\Finance
title: Finance
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'lfi/formations/finance/update/:id'
