title: ContactForm
modelClass: LFI\App\Models\ContactForm
list: $/lfi/app/models/contactform/columns.yaml
recordUrl: lfi/app/contactform/view/:id
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
defaultSort: 'created_at: desc'
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
