title: Professional
modelClass: Lfi\Formations\Models\Professional
list: $/lfi/formations/models/professional/columns.yaml
recordUrl: 'lfi/formations/professional/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
